//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT_UTEHY
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanBo
    {
        public int MaCB { get; set; }
        public string Hovaten { get; set; }
        public string Gioitinh { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string Quequan { get; set; }
        public Nullable<short> MaBM { get; set; }
        public string MaTD { get; set; }
        public string MaCV { get; set; }
        public string Email { get; set; }
        public string DT { get; set; }
        public byte[] Hinhanh { get; set; }
    
        public virtual BoMon BoMon { get; set; }
        public virtual ChucVu ChucVu { get; set; }
        public virtual TrinhDo TrinhDo { get; set; }
    }
}
